---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cephobjectstores.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephObjectStore
    listKind: CephObjectStoreList
    plural: cephobjectstores
    singular: cephobjectstore
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              dataPool:
                nullable: true
                properties:
                  compressionMode:
                    enum:
                    - ""
                    - none
                    - passive
                    - aggressive
                    - force
                    type: string
                  crushRoot:
                    type: string
                  erasureCoded:
                    nullable: true
                    properties:
                      codingChunks:
                        type: integer
                      dataChunks:
                        type: integer
                    type: object
                  failureDomain:
                    type: string
                  parameters:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  replicated:
                    nullable: true
                    properties:
                      replicasPerFailureDomain:
                        type: integer
                      requireSafeReplicaSize:
                        type: boolean
                      size:
                        type: integer
                      subFailureDomain:
                        type: string
                    type: object
                type: object
              gateway:
                properties:
                  annotations:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  externalRgwEndpoints:
                    items:
                      properties:
                        ip:
                          type: string
                      type: object
                    nullable: true
                    type: array
                  instances:
                    type: integer
                  labels:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  placement:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  port:
                    maximum: 65535
                    minimum: 0
                    type: integer
                  priorityClassName:
                    type: string
                  resources:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  securePort:
                    maximum: 65535
                    minimum: 0
                    type: integer
                  sslCertificateRef:
                    nullable: true
                    type: string
                  type:
                    type: string
                type: object
              healthCheck:
                nullable: true
                properties:
                  bucket:
                    nullable: true
                    properties:
                      enabled:
                        type: boolean
                      interval:
                        type: string
                    type: object
                type: object
              metadataPool:
                nullable: true
                properties:
                  compressionMode:
                    enum:
                    - ""
                    - none
                    - passive
                    - aggressive
                    - force
                    type: string
                  crushRoot:
                    type: string
                  erasureCoded:
                    nullable: true
                    properties:
                      codingChunks:
                        type: integer
                      dataChunks:
                        type: integer
                    type: object
                  failureDomain:
                    type: string
                  parameters:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  replicated:
                    nullable: true
                    properties:
                      replicasPerFailureDomain:
                        type: integer
                      requireSafeReplicaSize:
                        type: boolean
                      size:
                        type: integer
                      subFailureDomain:
                        type: string
                    type: object
                type: object
              preservePoolsOnDelete:
                type: boolean
              zone:
                properties:
                  name:
                    type: string
                type: object
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
