---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cephrbdmirrors.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephRBDMirror
    listKind: CephRBDMirrorList
    plural: cephrbdmirrors
    singular: cephrbdmirror
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              annotations:
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              count:
                maximum: 100
                minimum: 1
                type: integer
              peers:
                properties:
                  secretNames:
                    items:
                      type: string
                    type: array
                type: object
              placement:
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              priorityClassName:
                type: string
              resources:
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
