---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cephfilesystems.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephFilesystem
    listKind: CephFilesystemList
    plural: cephfilesystems
    singular: cephfilesystem
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Number of desired active MDS daemons
      jsonPath: .spec.metadataServer.activeCount
      name: ActiveMDS
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              dataPools:
                items:
                  properties:
                    compressionMode:
                      enum:
                      - ""
                      - none
                      - passive
                      - aggressive
                      - force
                      type: string
                    crushRoot:
                      type: string
                    deviceClass:
                      type: string
                    erasureCoded:
                      nullable: true
                      properties:
                        codingChunks:
                          maximum: 10
                          minimum: 0
                          type: integer
                        dataChunks:
                          maximum: 10
                          minimum: 0
                          type: integer
                      type: object
                    failureDomain:
                      type: string
                    parameters:
                      nullable: true
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    replicated:
                      nullable: true
                      properties:
                        replicasPerFailureDomain:
                          type: integer
                        requireSafeReplicaSize:
                          type: boolean
                        size:
                          maximum: 10
                          minimum: 0
                          type: integer
                        subFailureDomain:
                          type: string
                      type: object
                  type: object
                nullable: true
                type: array
              metadataPool:
                nullable: true
                properties:
                  compressionMode:
                    enum:
                    - ""
                    - none
                    - passive
                    - aggressive
                    - force
                    type: string
                  crushRoot:
                    type: string
                  deviceClass:
                    type: string
                  erasureCoded:
                    nullable: true
                    properties:
                      codingChunks:
                        maximum: 10
                        minimum: 0
                        type: integer
                      dataChunks:
                        maximum: 10
                        minimum: 0
                        type: integer
                    type: object
                  failureDomain:
                    type: string
                  parameters:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  replicated:
                    nullable: true
                    properties:
                      replicasPerFailureDomain:
                        type: integer
                      requireSafeReplicaSize:
                        type: boolean
                      size:
                        maximum: 10
                        minimum: 0
                        type: integer
                      subFailureDomain:
                        type: string
                    type: object
                type: object
              metadataServer:
                properties:
                  activeCount:
                    maximum: 10
                    minimum: 1
                    type: integer
                  activeStandby:
                    type: boolean
                  annotations:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  labels:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  placement:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  priorityClassName:
                    type: string
                  resources:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                type: object
              preserveFilesystemOnDelete:
                type: boolean
              preservePoolsOnDelete:
                type: boolean
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
