---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cephnfses.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephNFS
    listKind: CephNFSList
    plural: cephnfses
    shortNames:
    - nfs
    singular: cephnfs
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              rados:
                properties:
                  namespace:
                    type: string
                  pool:
                    type: string
                type: object
              server:
                properties:
                  active:
                    type: integer
                  annotations:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  logLevel:
                    type: string
                  placement:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  priorityClassName:
                    type: string
                  resources:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                type: object
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
