apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocs-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ocs-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: ocs-operator
    spec:
      serviceAccountName: ocs-operator
      containers:
        - name: ocs-operator
          # Replace this with the built image name
          image: ocs-dev/ocs-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - ocs-operator
          args:
          - --enable-leader-election
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 10


