---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephblockpools.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephBlockPool
    listKind: CephBlockPoolList
    plural: cephblockpools
    singular: cephblockpool
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            compressionMode:
              enum:
              - ""
              - none
              - passive
              - aggressive
              - force
              type: string
            crushRoot:
              type: string
            enableRBDStats:
              description: EnableRBDStats is used to enable gathering of statistics
                for all RBD images in the pool
              type: boolean
            erasureCoded:
              properties:
                codingChunks:
                  maximum: 9
                  minimum: 0
                  type: integer
                dataChunks:
                  maximum: 9
                  minimum: 0
                  type: integer
            failureDomain:
              type: string
            parameters:
              type: object
            replicated:
              properties:
                requireSafeReplicaSize:
                  type: boolean
                size:
                  maximum: 9
                  minimum: 0
                  type: integer
                targetSizeRatio:
                  type: number
  version: v1
