---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephobjectstores.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephObjectStore
    listKind: CephObjectStoreList
    plural: cephobjectstores
    singular: cephobjectstore
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            dataPool:
              properties:
                compressionMode:
                  enum:
                  - ""
                  - none
                  - passive
                  - aggressive
                  - force
                  type: string
                crushRoot:
                  type: string
                erasureCoded:
                  properties:
                    codingChunks:
                      type: integer
                    dataChunks:
                      type: integer
                failureDomain:
                  type: string
                parameters:
                  type: object
                replicated:
                  properties:
                    requireSafeReplicaSize:
                      type: boolean
                    size:
                      type: integer
            gateway:
              properties:
                annotations: {}
                externalRgwEndpoints:
                  items:
                    properties:
                      ip:
                        type: string
                  type: array
                instances:
                  type: integer
                placement: {}
                port:
                  maximum: 65535
                  minimum: 1
                  type: integer
                resources: {}
                securePort: {}
                sslCertificateRef: {}
                type:
                  type: string
            healthCheck:
              properties:
                bucket:
                  properties:
                    enabled:
                      type: boolean
                    interval:
                      type: string
            metadataPool:
              properties:
                compressionMode:
                  enum:
                  - ""
                  - none
                  - passive
                  - aggressive
                  - force
                  type: string
                crushRoot:
                  type: string
                erasureCoded:
                  properties:
                    codingChunks:
                      type: integer
                    dataChunks:
                      type: integer
                failureDomain:
                  type: string
                parameters:
                  type: object
                replicated:
                  properties:
                    requireSafeReplicaSize:
                      type: boolean
                    size:
                      type: integer
            preservePoolsOnDelete:
              type: boolean
  version: v1
