# permissions for end users to view ocsinitializations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocsinitialization-viewer-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - ocsinitializations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - ocsinitializations/status
  verbs:
  - get
