# permissions for end users to edit ocsinitializations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocsinitialization-editor-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - ocsinitializations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - ocsinitializations/status
  verbs:
  - get
