# permissions for end users to view storageclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storagecluster-viewer-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclusters/status
  verbs:
  - get
