# permissions for end users to edit storageclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storagecluster-editor-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclusters/status
  verbs:
  - get
