apiVersion: ocs.openshift.io/v1alpha1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: example-storagecluster
spec:
  manageNodes: false
  storageDeviceSets:
  - name: example-deviceset
    count: 3
    resources: {}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: gp2
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 1Ti
